### ISSUE TITLE
Create admin UI

### ISSUE THREAD

**Issue by rmccue** [humanmade/WordPress-Importer#1]
Right now, the Importer is missing a key component: the web interface. It's only runnable through WP-CLI right now. This sucks :(

I'd like to go further than just replicating the existing UI in the older version of the importer. I think we can make some real strides forward in providing a better UI, esp. with the resumable parsing we have. We should be able to avoid timeouts by running the import through Ajax, and resuming them (with a new request) whenever we get close to the timeout limit.

**Comment by melchoyce** [comment]
For some design reference, the Calypso importer is pretty nice: https://cloudup.com/cWNtcPQok6U

**Comment by rmccue** [comment]
@melchoyce See #30 :)

**Comment by melchoyce** [comment]
Sorry, missed that

**Comment by rmccue** [comment]
Sorted in #26!
