### ISSUE TITLE
Dependency on the old WordPress importer

### ISSUE THREAD

**Issue by drebbits** [humanmade/WordPress-Importer#11]
Is this going to be used alongside the old wordpress importer plugin? I tried to clone it while removing the importer plugin but it seems like the v2 is looking for the old wordpress-importer.php.

**Comment by michaelbragg** [comment]
I had the same issue. Removed the old plugin and couldn't activate the new version. Re-installed the old version, renamed the new version's folder. Then it would activate nicely.

If this is correct. Could I suggest incorporating this into the readme document.

**Comment by rmccue** [comment]
Whoops, this is totally unintentional! I'm accidentally loading the wrong file in. :|

**Comment by drebbits** [comment]
That was fast ;)
