### ISSUE TITLE
Failed to import media

### ISSUE THREAD

**Issue by paaljoachim** [humanmade/WordPress-Importer#112]
I tried importing posts that include media but the media is not imported.

![screen shot 2017-06-02 at 13 56 38](https://cloud.githubusercontent.com/assets/5323259/26724751/5712b678-479b-11e7-8d2d-87bbc98aae8f.png)

It links to the original site the images came from instead of importing the images.

**Comment by swissspidy** [comment]
Hi there,

As noted on Slack, it seems like you're using the official WordPress Importer (the one available at https://wordpress.org/plugins/wordpress-importer/), and not this new one.

I suggest you to try this one instead as it likely fixes these problems.

Cheers!

**Comment by paaljoachim** [comment]
Thanks Pascal! I will now test the correct plugin..:)

**Comment by CM-1207** [comment]
It does not work.
