### ISSUE TITLE
Using inside a theme

### ISSUE THREAD

**Issue by anteksiler** [humanmade/WordPress-Importer#12]
Thanks Ryan, this has been long overdue and WordPress community loves you for all your work!

I usually use the importer inside a theme to import the theme demo files. How can I utilize this version? 

With version 0.6, I am using:

```
$file = get_template_directory() ."/inc/democontent/demo-content.xml";
$importer = new WP_Import();
$importer->fetch_attachments = true;
$importer->import($file);
```

**Comment by rmccue** [comment]
Thanks :)

The [CLI command](https://github.com/humanmade/WordPress-Importer/blob/master/class-command.php) is a good example of how to use it, so something like this...

```php
$importer = new WXR_Importer(array(
	'fetch_attachments' => true,
));
$importer->import($file);
```

(You can also set the logger via `$importer->set_logger()` :) )

**Comment by anteksiler** [comment]
@rmccue Hi Ryan, thanks for the code snippet, I have included the importer as shown:
```
if ( is_admin() ) {
	if ( ! class_exists( 'WP_Importer' ) ) {
		defined( 'WP_LOAD_IMPORTERS' ) || define( 'WP_LOAD_IMPORTERS', true );
		require ABSPATH . 'wp-admin/includes/class-wp-importer.php';
	}
	
	require_once('inc/wordpress-importer/class-logger.php');
	require_once('inc/wordpress-importer/class-logger-cli.php');
	require_once('inc/wordpress-importer/class-wxr-importer.php');
}
```
And then used your code, but I failed to import any content.

**Comment by anteksiler** [comment]
@rmccue Hi Ryan, have you had a chance to look at this? I still am not able to import any content.
