### ISSUE TITLE
Log in a file too

### ISSUE THREAD

**Issue by Rahe** [humanmade/WordPress-Importer#13]
Hi,

When i'm logging, i'm logging in a file for being able to store all the results of an import and check everything was fine, this can be usefull especially if the import is something automated.

For this I'm using this script of my creation https://github.com/BeAPI/bea-logger, it works like yours (logging levels etc.) .
Maybe implementing something like this can be usefull ?

Thanks for the work on this subject :)

**Comment by rmccue** [comment]
The logger interface here is actually [PSR-3-compatible](http://www.php-fig.org/psr/psr-3/), so you can use existing projects here like [monolog](https://github.com/Seldaek/monolog) with no trouble. :)

Specifically for this use case, if you're running the importer from the command line, `tee` is incredibly helpful:
```bash
wp wxr-importer import file.xml | tee import.log
```
This will output the log to stdout as it goes, as well as saving a copy to the file. :)

Once we get the admin UI working in #1, logging to a file is probably something we'll want to do too. I'll definitely keep it in mind. Thanks for the comment!
