### ISSUE TITLE
WP_Importer_Logger_ServerSentEvents doesn't work in IE10/11 and Edge

### ISSUE THREAD

**Issue by pbiron** [humanmade/WordPress-Importer#139]
IE10, IE11 and Edge do not implement [EventSource](http://caniuse.com/#search=eventsource), hence the ServeSentEvents logger doesn't work in those browsers...and hence, those browsers can't be used for interactive imports.

**Comment by rmccue** [comment]
IE is now gone, and Edge supports SSE, closing.

**Comment by siegok** [comment]
![sonaya](https://user-images.githubusercontent.com/95343672/223126300-96e8394d-440f-438a-a1aa-f6cd02d6f20f.png)
