### ISSUE TITLE
Success/Fail callback

### ISSUE THREAD

**Issue by anteksiler** [humanmade/WordPress-Importer#14]
It would be nice to have a callback function that we can utilize at the end of the import function.

What do you guys think?

**Comment by rmccue** [comment]
There's an action at the start (currently `import_start`, although that may change) and one at the end (`import_end`) that you can use. Is there a use case for supporting more here? :)

**Comment by rmccue** [comment]
Closing this one out, see above actions. @anteksiler Thanks for filing the issue. :)
