### ISSUE TITLE
Class 'WP_Import' not found

### ISSUE THREAD

**Issue by drebbits** [humanmade/WordPress-Importer#15]
Getting this error somewhere in the plugin.php line 33. I believe it should be `WP_Importer`?

**Comment by drebbits** [comment]
Also - i'm testing this on VIPQS :)

**Comment by danielbachhuber** [comment]
Is the WordPress Importer plugin installed and activated?

**Comment by danielbachhuber** [comment]
> Is the WordPress Importer plugin installed and activated?

Sorry, this might be an erroneous suggestion. Testing.

**Comment by drebbits** [comment]
VIPQS is on WP v4.4 beta4

**Comment by danielbachhuber** [comment]
I can reproduce. I'm not sure of the history though (as the code was introduced in a massive commit 73da8c43aa3750d02854d77e7258cc43fb5f0f2d), so we'll need to wait to hear of @rmccue's intensions.

**Comment by szaqal83** [comment]
I think line 33 should be:
```
$GLOBALS['wp_import_v2'] = new WXR_Importer();
```
doing so results: Undefined index: wp_import. So this should also be fixed.

Whole function should look like this:
```
function wpimportv2_init() {
	/**
	 * WordPress Importer object for registering the import callback
	 * @global WP_Import $wp_import
	 */
	$GLOBALS['wp_import_v2'] = new WXR_Importer();
	register_importer(
		'wordpress-v2',
		'WordPress (v2)',
		__('Import <strong>posts, pages, comments, custom fields, categories, and tags</strong> from a WordPress export file.', 'wordpress-importer'),
		array( $GLOBALS['wp_import_v2'], 'dispatch' )
	);
}
```

**Comment by rmccue** [comment]
If you're hitting this on the admin import screen, then yeah, see #1 (the admin hasn't been touched at all yet). I think that's the only time this mistake is made?

**Comment by szaqal83** [comment]
No I was runing it from WP CLI.

**Comment by rmccue** [comment]
@szaqal83 Thanks for clarifying, will investigate. Are you running the `wp wxr-importer import` command here, or a different command?

**Comment by szaqal83** [comment]
Yes, exactly.

**Comment by rlaan** [comment]
Hi all,

I got the same error and solved it with also installing the former wp-importer plugin. 
I am not sure at all if that was how it should work (probably not), but I was just guessing the new version was like a 'on-top-of' kind a plugin.

**Comment by lkraav** [comment]
Also hitting this. Network-activating old Importer doesn't seem to help.

**Comment by ManiKumar01** [comment]
Fatal error: Class 'WP_Import' 

WordPress-Importer-master\plugin.php on line 33

**Comment by ptasker** [comment]
Added a PR that wraps the WP_Import call in a class_exists check.

**Comment by dimbak** [comment]
I think this is now fixed in this branch https://github.com/humanmade/WordPress-Importer/tree/admin-ui

**Comment by rmccue** [comment]
This is totally fixed now. :)
