### ISSUE TITLE
Add support for composer

### ISSUE THREAD

**Issue by franz-josef-kaiser** [humanmade/WordPress-Importer#20]
It's really tough battle-testing this importer without support for Composer. We need that.

**Comment by franz-josef-kaiser** [comment]
See PR #21

**Comment by franz-josef-kaiser** [comment]
@rmccue Ping. Could you please at least label that issue so I can see the status in my issue and PR overview? Thanks.

**Comment by swissspidy** [comment]
Nothing wrong with adding composer support IMHO. Also of use for #55 for example. We should keep it simple though.

**Comment by franz-josef-kaiser** [comment]
Done with 0e329e0 and previous commits.
