### ISSUE TITLE
Some trac bugs that may interest you

### ISSUE THREAD

**Issue by theMikeD** [humanmade/WordPress-Importer#29]
FYI

https://core.trac.wordpress.org/ticket/36342

https://core.trac.wordpress.org/ticket/36340

https://core.trac.wordpress.org/ticket/36339

**Comment by rmccue** [comment]
Thanks for noting these tickets here! As @ntwb noted, these are on the export side, so they're not needed here. The importer and exporter work pretty independently, although they're obviously linked.

Feel free to open new tickets if anything needs doing on the importer side.

**Comment by theMikeD** [comment]
I should have been more specific. I mention the here because they are good indicators of weird unexpected behaviour that somehow made it into core, and as a suggestion that similarly weird decisions should be avoided here :)  Good luck with the project.
