### ISSUE TITLE
Import missing posts and imported users twice

### ISSUE THREAD

**Issue by colinduwe** [humanmade/WordPress-Importer#33]
I gave the new importer a shot. However, my export file contains 884 posts but it only found 1. And strangely it imported the users twice.
![screen shot 2016-04-12 at 1 02 10 pm](https://cloud.githubusercontent.com/assets/2152870/14473911/4519cc7e-00af-11e6-97e0-a5e041d9400f.png)

**Comment by bobbingwide** [comment]
I also have twice as many users ( completed 2/1 ).
But I also received "error	Failed to import user - _username_"
twice so it's unclear what the problem was.

**Comment by colinduwe** [comment]
My issue appears to be caused by a bad export .xml file. I can't seem to get my source blog to export valid XML.
