### ISSUE TITLE
NaN% for 0 comments - import doesn't start

### ISSUE THREAD

**Issue by bobbingwide** [humanmade/WordPress-Importer#40]
Uncaught TypeError: Failed to set the 'value' property on 'HTMLProgressElement': The provided double value is non-finite.

**Comment by bobbingwide** [comment]
Local temporary workaround. 

I fixed import.js, in updateProgress, set total to 1 if it's 0.

I may create some PR's later.

**Comment by lmartins** [comment]
Im not sure if related to this but tried importing pages and posts and none of them worked. 

I get a few PHP warnings and the progress box doesn't go past this:

![screenshot 2016-04-19 14 49 43](https://cloud.githubusercontent.com/assets/151981/14641405/fcee5c78-063d-11e6-81d4-fa88efb00e60.png)

Thanks.

**Comment by anhskohbo** [comment]
I have same issues

**Comment by swissspidy** [comment]
@bobbingwide Thanks for your report! I saw the commit above in your fork. Has it been working for you so far?

It would be great if we could turn it into a pull request. Some notes:

* All instances of `parseInt()` should always be called with the base set, e.g. `parseInt( total, 10 )`.
* I'd make the condition more specific: `if ( 0 === total || isNaN(total) ) { …`.
* The indentation in bobbingwide/WordPress-Importer@2a7cec40c0f4df80b74d31a3b05eee3f9fc866ef looks odd.

**Comment by cgrymala** [comment]
This issue exists if any of the items that the importer handles are 0. I've tested with 0 taxonomy terms, 0 media items, 0 authors, etc. If any of those items are not present in the WXR file, the importer fails to start because of the NAN JavaScript error.

**Comment by brianjohnsondesign** [comment]
I have experienced the same issue, same error, everything. The 0 comments is what triggered it for me it would seem.

**Comment by slaFFik** [comment]
Same error 
![image](https://cloud.githubusercontent.com/assets/282234/15724379/6ff3cdec-284f-11e6-8249-e913ade77ce8.png)
