### ISSUE TITLE
Follow WordPress Coding Standards

### ISSUE THREAD

**Issue by swissspidy** [humanmade/WordPress-Importer#55]
The code looks great already, but we should still add PHP CodeSniffer together with the WordPress Coding Standards project. See https://github.com/WP-API/WP-API for an example of how to implement this using composer (see also #20).

**Comment by franz-josef-kaiser** [comment]
Static target link [to git blob](https://github.com/WP-API/WP-API/blob/8b7864a205590a022fb44c5a1350ba467c8ab9f1/composer.json#L20-L30).
