### ISSUE TITLE
WP-CLI Support

### ISSUE THREAD

**Issue by lukecav** [humanmade/WordPress-Importer#66]
Would adding WP-CLI support so that you could import a file by command. Be a feature of use?

Granted this would be more advance use, but plugins like WP Migrate DB Pro have WP-CLI support.

**Comment by ntwb** [comment]
WP-CLI support is already here, `wp wxr-importer ...`, just undocumented, see #9

**Comment by ntwb** [comment]
p.s. I should have linked here: https://github.com/humanmade/WordPress-Importer#via-the-cli
