### ISSUE TITLE
Import from External URL

### ISSUE THREAD

**Issue by lukecav** [humanmade/WordPress-Importer#67]
Would it be possible to be add the function to be able to import the backup file from an external sources like

Google Drive
OneDrive
Dropbox
Amazon S3

**Comment by ntwb** [comment]
That is a lot of work for what would be used only once, typically a site will only ever need to import data once.

**Comment by rmccue** [comment]
This is a pretty niche use case and doesn't really fit the 80/20 use case. You can always download the file from one of these services first, so it's always possible to do it, just not in the most efficient way.

**Comment by lukecav** [comment]
But this would be use for users that have larger files to upload, then the upload would be served from the externally hosted file.
