### ISSUE TITLE
Failed to import media in WP 4.6

### ISSUE THREAD

**Issue by relstudiosnx** [humanmade/WordPress-Importer#80]
I recently added a code to support xml file on my theme and later found that, images are being failed to import for the importer plugin ?? Does anybody has faced this issue before ?  http://prntscr.com/cc0i8w

Also i found this warning while importing http://prntscr.com/cc03it 

Any help will be appreciated.

Thanks

**Comment by raphaelkross** [comment]
@relstudiosnx could you let me know if this behavior is still happening at 4.6.1?!

Besides, can you share the XML with error?

**Comment by relstudiosnx** [comment]
@raphaelkross i am really very sorry, actually the problem was with my server.

Thank your for your time and help.

**Comment by raphaelkross** [comment]
@relstudiosnx no problem - glad to know. I guess this one is just an invalid report!

**Comment by sreekanthgs** [comment]
Can someone please mark this resolved/closed?
