### ISSUE TITLE
Importer not correctly processing Elementor post meta

### ISSUE THREAD

**Issue by colmtroy** [humanmade/WordPress-Importer#93]
Hi folks,

Just identified a possible bug - full issue described here - I originally thought it was a bug with that plugin but I've also confirmed the issue persists with WP Importer 2.0 - which the plugin in the thread below leverages.

https://wordpress.org/support/topic/elementor-metadata-not-being-applied-to-content/

If you need any further details to re-create the issue let me know.

Best,

Colm

**Comment by matipojo** [comment]
Hi, 

It's a problem with JSON meta values. The `add_post_meta` removes the JSON escaped strings ( with `wp_unslash`).

In Elementor we added a filter for the **Wordpress Importer** hook `wp_import_post_meta`:
https://github.com/pojome/elementor/blob/develop/includes/compatibility.php#L62

Thanks,
Mati

**Comment by colmtroy** [comment]
Hey Mati,

Thanks for the fast reply - aha - any plans to add a similar filter for the new importer? I understand WP Importer 2 will eventually replace the current WordPress Importer.

Colm

**Comment by matipojo** [comment]
Ofcourse, we will handle it.

**Comment by colmtroy** [comment]
@matipojo Super - thanks!

**Comment by rmccue** [comment]
@matipojo Is this an issue in the Importer itself? i.e. is the Importer incorrectly slashing/unslashing here? If so, it definitely needs to be fixed here.

**Comment by carstingaxion** [comment]
> @matipojo  [...] we added a filter for the **Wordpress Importer** hook `wp_import_post_meta`

I ran into the same issue now, while using WordPress playground, which comes with _this_ importer by default. 

I'm also using `wp_import_post_meta` and was wondering, why my post_meta is missing on an `importFile` step.

But [**this hook is not part of _this_ importer anymore**](https://github.com/search?q=repo%3Ahumanmade%2FWordPress-Importer%20wp_import_post_meta&type=code), which is indeed a problem, that should be fixed here @rmccue .

**Comment by carstingaxion** [comment]
I’ll suggest adding at least a [apply_filters_deprecated()](https://developer.wordpress.org/reference/functions/apply_filters_deprecated/) call somewhere next to

```php
/**
			 * Pre-process post meta data.
			 *
			 * @param array $meta_item Meta data. (Return empty to skip.)
			 * @param int $post_id Post the meta is attached to.
			 */
			$meta_item = apply_filters( 'wxr_importer.pre_process.post_meta', $meta_item, $post_id );
```
